GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE
TO HTA;

GRANT CONNECT, RESOURCE
TO HTA;


GRANT CREATE SYNONYM, DROP ANY SYSNONYM
TO HTA;

CREATE TABLE --자신 소유의 테이블을 생성하는 시스템 권한
CREATE ANY TABLE --임의의 소유테이블을 생성하는 시스템 권한

DROP TABLE
DROP ANY TABLE